from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),
    path('calculators/molecular-weight/', views.molecular_weight, name='molecular_weight'),
    path('calculators/molarity/', views.molarity, name='molarity'),
    path('calculators/ph/', views.ph_calculator, name='ph_calculator'),
    path('calculators/ideal-gas/', views.ideal_gas, name='ideal_gas'),
    path('calculators/', views.calculator_list, name='calculator_list'),
    path('calculators/neutralization/', views.neutralization, name='neutralization'),
    path('calculators/percent-yield/', views.percent_yield, name='percent_yield'),
    path('calculators/half-life/', views.half_life, name='half_life'),
    path('calculators/boyles-law/', views.boyles_law, name='boyles_law'),
    path('calculators/dilution-factor/', views.dilution_factor, name='dilution_factor'),
    path('calculators/mass-percent/', views.mass_percent, name='mass_percent'),
    path('calculators/mixing-ratio/', views.mixing_ratio, name='mixing_ratio'),
    path('calculators/serial-dilution/', views.serial_dilution, name='serial_dilution'),
    path('calculators/solution-dilution/', views.solution_dilution, name='solution_dilution'),
    path('calculators/buffer-capacity/', views.buffer_capacity, name='buffer_capacity'),
    path('calculators/nernst-equation/', views.nernst_equation, name='nernst_equation'),
    path('calculators/ionic-strength/', views.ionic_strength, name='ionic_strength'),
    path('calculators/electrolysis/', views.electrolysis, name='electrolysis'),
    path('calculators/chemical-name/', views.chemical_name, name='chemical_name'),
    path('calculators/effective-nuclear-charge/', views.effective_nuclear_charge, name='effective_nuclear_charge'),
    path('calculators/electron-configuration/', views.electron_configuration, name='electron_configuration'),
    path('calculators/electronegativity/', views.electronegativity, name='electronegativity'),
    path('calculators/activation-energy/', views.activation_energy, name='activation_energy'),
    path('calculators/arrhenius/', views.arrhenius, name='arrhenius'),
    path('calculators/equilibrium-constant/', views.equilibrium_constant, name='equilibrium_constant'),
    path('calculators/kp/', views.kp_constant, name='kp_constant'),
    path('calculators/actual-yield/', views.actual_yield, name='actual_yield'),
    path('api/chat/', views.chat_api, name='chat_api'),
    path('api/register/', views.api_register, name='api_register'),
    path('api/login/', views.api_login, name='api_login'),
    path('api/me/', views.api_me, name='api_me'),
    path('forum/', views.forum_home, name='forum_home'),
    path('api/forum/threads/', views.api_forum_threads, name='api_forum_threads'),
    path('api/forum/answers/', views.api_forum_answers, name='api_forum_answers'),
    path('api/forum/vote-answer/', views.api_forum_vote_answer, name='api_forum_vote_answer'),
    path('api/forum/report/', views.api_forum_report, name='api_forum_report'),
]
